# Generated by Django 5.0.7 on 2024-08-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Date_of_Birth',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileImage/noprofile.png', upload_to='profileImage'),
        ),
    ]
